services:
  - type: web
    name: chai-pmtct
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node .next/standalone/server.js
    envVars:
      - key: DATABASE_URL
        value: file:./dev.db
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false
      - key: NODE_ENV
        value: production
